-- Update countries with region (continent) classification
UPDATE countries SET region = 'Asia' WHERE name = 'Afghanistan';
UPDATE countries SET region = 'Asia' WHERE name = 'Azerbaijan';
UPDATE countries SET region = 'Asia' WHERE name = 'Bahrain';
UPDATE countries SET region = 'Asia' WHERE name = 'Bangladesh';
UPDATE countries SET region = 'Asia' WHERE name = 'Bhutan';
UPDATE countries SET region = 'Asia' WHERE name = 'Brunei';
UPDATE countries SET region = 'Asia' WHERE name = 'Cambodia';
UPDATE countries SET region = 'Asia' WHERE name = 'China';
UPDATE countries SET region = 'Asia' WHERE name = 'Comoros';
UPDATE countries SET region = 'Asia' WHERE name = 'Cyprus';
UPDATE countries SET region = 'Asia' WHERE name = 'Georgia';
UPDATE countries SET region = 'Asia' WHERE name = 'Hong Kong';
UPDATE countries SET region = 'Asia' WHERE name = 'India';
UPDATE countries SET region = 'Asia' WHERE name = 'Indonesia';
UPDATE countries SET region = 'Asia' WHERE name = 'Iran';
UPDATE countries SET region = 'Asia' WHERE name = 'Iraq';
UPDATE countries SET region = 'Asia' WHERE name = 'Israel';
UPDATE countries SET region = 'Asia' WHERE name = 'Japan';
UPDATE countries SET region = 'Asia' WHERE name = 'Jordan';
UPDATE countries SET region = 'Asia' WHERE name = 'Kazakhstan';
UPDATE countries SET region = 'Asia' WHERE name = 'Kuwait';
UPDATE countries SET region = 'Asia' WHERE name = 'Kyrgyzstan';
UPDATE countries SET region = 'Asia' WHERE name = 'Laos';
UPDATE countries SET region = 'Asia' WHERE name = 'Lebanon';
UPDATE countries SET region = 'Asia' WHERE name = 'Macau';
UPDATE countries SET region = 'Asia' WHERE name = 'Malaysia';
UPDATE countries SET region = 'Asia' WHERE name = 'Maldives';
UPDATE countries SET region = 'Asia' WHERE name = 'Mongolia';
UPDATE countries SET region = 'Asia' WHERE name = 'Myanmar';
UPDATE countries SET region = 'Asia' WHERE name = 'Nepal';
UPDATE countries SET region = 'Asia' WHERE name = 'North Korea';
UPDATE countries SET region = 'Asia' WHERE name = 'Oman';
UPDATE countries SET region = 'Asia' WHERE name = 'Pakistan';
UPDATE countries SET region = 'Asia' WHERE name = 'Palau';
UPDATE countries SET region = 'Asia' WHERE name = 'Palestine';
UPDATE countries SET region = 'Asia' WHERE name = 'Philippines';
UPDATE countries SET region = 'Asia' WHERE name = 'Qatar';
UPDATE countries SET region = 'Asia' WHERE name = 'Saudi Arabia';
UPDATE countries SET region = 'Asia' WHERE name = 'Singapore';
UPDATE countries SET region = 'Asia' WHERE name = 'South Korea';
UPDATE countries SET region = 'Asia' WHERE name = 'Sri Lanka';
UPDATE countries SET region = 'Asia' WHERE name = 'Syria';
UPDATE countries SET region = 'Asia' WHERE name = 'Taiwan';
UPDATE countries SET region = 'Asia' WHERE name = 'Tajikistan';
UPDATE countries SET region = 'Asia' WHERE name = 'Thailand';
UPDATE countries SET region = 'Asia' WHERE name = 'Timor-Leste';
UPDATE countries SET region = 'Asia' WHERE name = 'Turkey';
UPDATE countries SET region = 'Asia' WHERE name = 'Turkmenistan';
UPDATE countries SET region = 'Asia' WHERE name = 'United Arab Emirates';
UPDATE countries SET region = 'Asia' WHERE name = 'Uzbekistan';
UPDATE countries SET region = 'Asia' WHERE name = 'Vietnam';
UPDATE countries SET region = 'Asia' WHERE name = 'Yemen';
UPDATE countries SET region = 'Europe' WHERE name = 'Albania';
UPDATE countries SET region = 'Europe' WHERE name = 'Andorra';
UPDATE countries SET region = 'Europe' WHERE name = 'Austria';
UPDATE countries SET region = 'Europe' WHERE name = 'Belarus';
UPDATE countries SET region = 'Europe' WHERE name = 'Belgium';
UPDATE countries SET region = 'Europe' WHERE name = 'Bosnia and Herzegovina';
UPDATE countries SET region = 'Europe' WHERE name = 'Bulgaria';
UPDATE countries SET region = 'Europe' WHERE name = 'Croatia';
UPDATE countries SET region = 'Europe' WHERE name = 'Czech Republic';
UPDATE countries SET region = 'Europe' WHERE name = 'Denmark';
UPDATE countries SET region = 'Europe' WHERE name = 'Estonia';
UPDATE countries SET region = 'Europe' WHERE name = 'Faroe Islands';
UPDATE countries SET region = 'Europe' WHERE name = 'Finland';
UPDATE countries SET region = 'Europe' WHERE name = 'France';
UPDATE countries SET region = 'Europe' WHERE name = 'Germany';
UPDATE countries SET region = 'Europe' WHERE name = 'Gibraltar';
UPDATE countries SET region = 'Europe' WHERE name = 'Greece';
UPDATE countries SET region = 'Europe' WHERE name = 'Guernsey';
UPDATE countries SET region = 'Europe' WHERE name = 'Hungary';
UPDATE countries SET region = 'Europe' WHERE name = 'Iceland';
UPDATE countries SET region = 'Europe' WHERE name = 'Ireland';
UPDATE countries SET region = 'Europe' WHERE name = 'Isle of Man';
UPDATE countries SET region = 'Europe' WHERE name = 'Italy';
UPDATE countries SET region = 'Europe' WHERE name = 'Jersey';
UPDATE countries SET region = 'Europe' WHERE name = 'Kosovo';
UPDATE countries SET region = 'Europe' WHERE name = 'Latvia';
UPDATE countries SET region = 'Europe' WHERE name = 'Liechtenstein';
UPDATE countries SET region = 'Europe' WHERE name = 'Lithuania';
UPDATE countries SET region = 'Europe' WHERE name = 'Luxembourg';
UPDATE countries SET region = 'Europe' WHERE name = 'Malta';
UPDATE countries SET region = 'Europe' WHERE name = 'Moldova';
UPDATE countries SET region = 'Europe' WHERE name = 'Monaco';
UPDATE countries SET region = 'Europe' WHERE name = 'Montenegro';
UPDATE countries SET region = 'Europe' WHERE name = 'Netherlands';
UPDATE countries SET region = 'Europe' WHERE name = 'North Macedonia';
UPDATE countries SET region = 'Europe' WHERE name = 'Norway';
UPDATE countries SET region = 'Europe' WHERE name = 'Poland';
UPDATE countries SET region = 'Europe' WHERE name = 'Portugal';
UPDATE countries SET region = 'Europe' WHERE name = 'Romania';
UPDATE countries SET region = 'Europe' WHERE name = 'Russia';
UPDATE countries SET region = 'Europe' WHERE name = 'San Marino';
UPDATE countries SET region = 'Europe' WHERE name = 'Serbia';
UPDATE countries SET region = 'Europe' WHERE name = 'Slovakia';
UPDATE countries SET region = 'Europe' WHERE name = 'Slovenia';
UPDATE countries SET region = 'Europe' WHERE name = 'Spain';
UPDATE countries SET region = 'Europe' WHERE name = 'Svalbard';
UPDATE countries SET region = 'Europe' WHERE name = 'Sweden';
UPDATE countries SET region = 'Europe' WHERE name = 'Switzerland';
UPDATE countries SET region = 'Europe' WHERE name = 'Ukraine';
UPDATE countries SET region = 'Europe' WHERE name = 'United Kingdom';
UPDATE countries SET region = 'Europe' WHERE name = 'Vatican City';
UPDATE countries SET region = 'Africa' WHERE name = 'Algeria';
UPDATE countries SET region = 'Africa' WHERE name = 'Angola';
UPDATE countries SET region = 'Africa' WHERE name = 'Benin';
UPDATE countries SET region = 'Africa' WHERE name = 'Botswana';
UPDATE countries SET region = 'Africa' WHERE name = 'Burkina Faso';
UPDATE countries SET region = 'Africa' WHERE name = 'Burundi';
UPDATE countries SET region = 'Africa' WHERE name = 'Cameroon';
UPDATE countries SET region = 'Africa' WHERE name = 'Cape Verde';
UPDATE countries SET region = 'Africa' WHERE name = 'Central African Republic';
UPDATE countries SET region = 'Africa' WHERE name = 'Chad';
UPDATE countries SET region = 'Africa' WHERE name = 'Congo (Brazzaville)';
UPDATE countries SET region = 'Africa' WHERE name = 'Congo (Kinshasa)';
UPDATE countries SET region = 'Africa' WHERE name = 'Côte d Ivoire';
UPDATE countries SET region = 'Africa' WHERE name = 'Democratic Republic of the Congo';
UPDATE countries SET region = 'Africa' WHERE name = 'Djibouti';
UPDATE countries SET region = 'Africa' WHERE name = 'Egypt';
UPDATE countries SET region = 'Africa' WHERE name = 'Equatorial Guinea';
UPDATE countries SET region = 'Africa' WHERE name = 'Eritrea';
UPDATE countries SET region = 'Africa' WHERE name = 'Eswatini';
UPDATE countries SET region = 'Africa' WHERE name = 'Ethiopia';
UPDATE countries SET region = 'Africa' WHERE name = 'Gabon';
UPDATE countries SET region = 'Africa' WHERE name = 'Gambia';
UPDATE countries SET region = 'Africa' WHERE name = 'Ghana';
UPDATE countries SET region = 'Africa' WHERE name = 'Guinea';
UPDATE countries SET region = 'Africa' WHERE name = 'Guinea-Bissau';
UPDATE countries SET region = 'Africa' WHERE name = 'Kenya';
UPDATE countries SET region = 'Africa' WHERE name = 'Lesotho';
UPDATE countries SET region = 'Africa' WHERE name = 'Liberia';
UPDATE countries SET region = 'Africa' WHERE name = 'Libya';
UPDATE countries SET region = 'Africa' WHERE name = 'Madagascar';
UPDATE countries SET region = 'Africa' WHERE name = 'Malawi';
UPDATE countries SET region = 'Africa' WHERE name = 'Mali';
UPDATE countries SET region = 'Africa' WHERE name = 'Mauritania';
UPDATE countries SET region = 'Africa' WHERE name = 'Mauritius';
UPDATE countries SET region = 'Africa' WHERE name = 'Mayotte';
UPDATE countries SET region = 'Africa' WHERE name = 'Morocco';
UPDATE countries SET region = 'Africa' WHERE name = 'Mozambique';
UPDATE countries SET region = 'Africa' WHERE name = 'Namibia';
UPDATE countries SET region = 'Africa' WHERE name = 'Niger';
UPDATE countries SET region = 'Africa' WHERE name = 'Nigeria';
UPDATE countries SET region = 'Africa' WHERE name = 'Republic of the Congo';
UPDATE countries SET region = 'Africa' WHERE name = 'Reunion';
UPDATE countries SET region = 'Africa' WHERE name = 'Rwanda';
UPDATE countries SET region = 'Africa' WHERE name = 'São Tomé and Príncipe';
UPDATE countries SET region = 'Africa' WHERE name = 'Senegal';
UPDATE countries SET region = 'Africa' WHERE name = 'Seychelles';
UPDATE countries SET region = 'Africa' WHERE name = 'Sierra Leone';
UPDATE countries SET region = 'Africa' WHERE name = 'Somalia';
UPDATE countries SET region = 'Africa' WHERE name = 'South Africa';
UPDATE countries SET region = 'Africa' WHERE name = 'South Sudan';
UPDATE countries SET region = 'Africa' WHERE name = 'Sudan';
UPDATE countries SET region = 'Africa' WHERE name = 'Tanzania';
UPDATE countries SET region = 'Africa' WHERE name = 'Togo';
UPDATE countries SET region = 'Africa' WHERE name = 'Tunisia';
UPDATE countries SET region = 'Africa' WHERE name = 'Uganda';
UPDATE countries SET region = 'Africa' WHERE name = 'Western Sahara';
UPDATE countries SET region = 'Africa' WHERE name = 'Zambia';
UPDATE countries SET region = 'Africa' WHERE name = 'Zimbabwe';
UPDATE countries SET region = 'North America' WHERE name = 'Bahamas';
UPDATE countries SET region = 'North America' WHERE name = 'Barbados';
UPDATE countries SET region = 'North America' WHERE name = 'Belize';
UPDATE countries SET region = 'North America' WHERE name = 'Bermuda';
UPDATE countries SET region = 'North America' WHERE name = 'Canada';
UPDATE countries SET region = 'North America' WHERE name = 'Cayman Islands';
UPDATE countries SET region = 'North America' WHERE name = 'Costa Rica';
UPDATE countries SET region = 'North America' WHERE name = 'Cuba';
UPDATE countries SET region = 'North America' WHERE name = 'Dominica';
UPDATE countries SET region = 'North America' WHERE name = 'Dominican Republic';
UPDATE countries SET region = 'North America' WHERE name = 'El Salvador';
UPDATE countries SET region = 'North America' WHERE name = 'Greenland';
UPDATE countries SET region = 'North America' WHERE name = 'Grenada';
UPDATE countries SET region = 'North America' WHERE name = 'Guadeloupe';
UPDATE countries SET region = 'North America' WHERE name = 'Guatemala';
UPDATE countries SET region = 'North America' WHERE name = 'Haiti';
UPDATE countries SET region = 'North America' WHERE name = 'Honduras';
UPDATE countries SET region = 'North America' WHERE name = 'Jamaica';
UPDATE countries SET region = 'North America' WHERE name = 'Martinique';
UPDATE countries SET region = 'North America' WHERE name = 'Mexico';
UPDATE countries SET region = 'North America' WHERE name = 'Nicaragua';
UPDATE countries SET region = 'North America' WHERE name = 'Panama';
UPDATE countries SET region = 'North America' WHERE name = 'Puerto Rico';
UPDATE countries SET region = 'North America' WHERE name = 'Saint Kitts and Nevis';
UPDATE countries SET region = 'North America' WHERE name = 'Saint Lucia';
UPDATE countries SET region = 'North America' WHERE name = 'Saint Vincent and the Grenadines';
UPDATE countries SET region = 'North America' WHERE name = 'Trinidad and Tobago';
UPDATE countries SET region = 'North America' WHERE name = 'USA';
UPDATE countries SET region = 'North America' WHERE name = 'United States';
UPDATE countries SET region = 'North America' WHERE name = 'US Virgin Islands';
UPDATE countries SET region = 'South America' WHERE name = 'Argentina';
UPDATE countries SET region = 'South America' WHERE name = 'Aruba';
UPDATE countries SET region = 'South America' WHERE name = 'Bolivia';
UPDATE countries SET region = 'South America' WHERE name = 'Brazil';
UPDATE countries SET region = 'South America' WHERE name = 'Chile';
UPDATE countries SET region = 'South America' WHERE name = 'Colombia';
UPDATE countries SET region = 'South America' WHERE name = 'Curaçao';
UPDATE countries SET region = 'South America' WHERE name = 'Ecuador';
UPDATE countries SET region = 'South America' WHERE name = 'French Guiana';
UPDATE countries SET region = 'South America' WHERE name = 'Guyana';
UPDATE countries SET region = 'South America' WHERE name = 'Paraguay';
UPDATE countries SET region = 'South America' WHERE name = 'Peru';
UPDATE countries SET region = 'South America' WHERE name = 'Suriname';
UPDATE countries SET region = 'South America' WHERE name = 'Uruguay';
UPDATE countries SET region = 'South America' WHERE name = 'Venezuela';
UPDATE countries SET region = 'Oceania' WHERE name = 'American Samoa';
UPDATE countries SET region = 'Oceania' WHERE name = 'Australia';
UPDATE countries SET region = 'Oceania' WHERE name = 'Fiji';
UPDATE countries SET region = 'Oceania' WHERE name = 'French Polynesia';
UPDATE countries SET region = 'Oceania' WHERE name = 'Guam';
UPDATE countries SET region = 'Oceania' WHERE name = 'Kiribati';
UPDATE countries SET region = 'Oceania' WHERE name = 'Marshall Islands';
UPDATE countries SET region = 'Oceania' WHERE name = 'Micronesia';
UPDATE countries SET region = 'Oceania' WHERE name = 'Nauru';
UPDATE countries SET region = 'Oceania' WHERE name = 'New Caledonia';
UPDATE countries SET region = 'Oceania' WHERE name = 'New Zealand';
UPDATE countries SET region = 'Oceania' WHERE name = 'Papua New Guinea';
UPDATE countries SET region = 'Oceania' WHERE name = 'Samoa';
UPDATE countries SET region = 'Oceania' WHERE name = 'Solomon Islands';
UPDATE countries SET region = 'Oceania' WHERE name = 'Tonga';
UPDATE countries SET region = 'Oceania' WHERE name = 'Tuvalu';
UPDATE countries SET region = 'Oceania' WHERE name = 'Vanuatu';
UPDATE countries SET region = 'Caribbean' WHERE name = 'Anguilla';
UPDATE countries SET region = 'Caribbean' WHERE name = 'Antigua and Barbuda';
UPDATE countries SET region = 'Caribbean' WHERE name = 'Aruba';
UPDATE countries SET region = 'Caribbean' WHERE name = 'British Virgin Islands';
UPDATE countries SET region = 'Caribbean' WHERE name = 'Turks and Caicos Islands';
UPDATE countries SET region = 'Other' WHERE name = 'Antarctica';